### ISSUE TITLE
How to debug with https://demos.openvidu.io/basic-videoconference/

### ISSUE THREAD

**Issue by razalur** [OpenVidu/openvidu-ios-app#3]
Hello!

Is it possible to show how it works with https://demos.openvidu.io/basic-videoconference/?
What url I need to input in ios app?

Best regards,
Aleksey.

**Comment by CSantosM** [comment]
Hello, 

As you know**, this app has several bugs and doesn't work properly**. If you want to contribute to fix it, the url that you're referencing is OpenVidu Server URL.

You can use https://demos.openvidu.io just for development propose.

**Comment by razalur** [comment]
But is it possible to connect from current iOS app to https://demos.openvidu.io? Or it doesn't? 
Now it fails any connection to htts. Does it need only wss? Or may by I do something wrong...
